services:
    site: 
        image: hugocarval/plcvision-site:1.8
        ports:
              - "80:3000"
        networks: 
              - rede-compose
        depends_on: 
              - db
    db: 
        image: hugocarval/mysql-plcvision:1.4
        ports:
              - "3307:3306"
        networks: 
              - rede-compose
networks:
    rede-compose:
        driver: bridge